### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by textbook** [textbook/impasse#1082]
There are two tests that keep failing in CI and on some local machines:

- `password API › returns 500 on unexpected errors`
- `password API › exposes whether a password has been pwned`

It's unclear what's causing this flakiness, if it's actually an edge case of the behaviour or something in the test framework, but it would be good to find out.
```
Run npm run test
  npm run test
  shell: /usr/bin/bash -e {0}

> impasse@0.10.6 test
> jest

PASS client client/src/App.test.js
FAIL server server/app.integration.test.js (17.406 s)
  ● Console

    console.log
      info: 	GET /api?min=[2](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:2)7&max=28 200 59.[3](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:3)[4](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:5)0 ms - 96

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

    console.log
      info: 	GET /api?min=7&max=7 200 16.092 ms - 60

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

    console.log
      info: 	GET /api?digits=3 200 20.291 ms - 66

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

    console.log
      info: 	GET /api?min=10&max=[5](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:6) 400 0.520 ms - 103

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

    console.log
      info: 	GET /api?digits=-2 400 0.430 ms - 84

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

    console.log
      info: 	GET /api?min=100&max=100 400 4.493 ms - 109

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

    console.log
      error: 	Error: oh no!
          at default (/home/runner/work/impasse/impasse/server/app.integration.test.js:90:11)
          at getPassword (/home/runner/work/impasse/impasse/server/password/service.js:18:19)
          at /home/runner/work/impasse/impasse/server/password/controller.js:97:12

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

    console.log
      info: 	GET /api 500 [6](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:7)4.480 ms - 21

      at Console.log (node_modules/winston/lib/winston/transports/console.js:[7](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:8)9:23)

    console.log
      info: 	GET /api 200 194.106 ms - 54

      at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)

  ● password API › returns 500 on unexpected errors

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      [8](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:9)3 | 	});
      84 |
    > 85 | 	it("returns 500 on unexpected errors", async () => {
         | 	^
      86 | 		jest.resetModules();
      87 | 		jest.doMock("./password/password", () => ({
      88 | 			__esModule: true,

      at it (server/app.integration.test.js:85:2)
      at Object.describe (server/app.integration.test.js:13:1)

  ● password API › exposes whether a password has been pwned

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       [9](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:10)6 | 	});
       97 |
    >  98 | 	it("exposes whether a password has been pwned", async () => {
          | 	^
       99 | 		const password = "password123";
      [10](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:11)0 | 		server.use(rest.get("https://api.pwnedpasswords.com/range/CBFDA", (req, res, ctx) => {
      101 | 			return res(ctx.status(200), ctx.text("C6008F9CAB4083784CBD1874F76618D2A97:[13](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:14)"));

      at it (server/app.integration.test.js:98:2)
      at Object.describe (server/app.integration.test.js:13:1)

PASS server server/password/config.test.js
PASS client client/src/services/passwordService.integration.test.js
PASS client client/src/Config.test.js
PASS client client/src/components/Strength.test.js
PASS server server/password/password.mock.test.js
PASS server server/password/password.test.js
PASS client client/src/components/Footer.test.js

Test Suites: 1 failed, 8 passed, 9 total
Tests:       2 failed, 51 passed, 53 total
Snapshots:   0 total
Time:        23.4[19](https://github.com/textbook/impasse/runs/6492942005?check_suite_focus=true#step:7:20) s
Ran all test suites in 2 projects.
Error: Process completed with exit code 1.
```

**Comment by textbook** [comment]
This seems to have gone away, closing for now.
